/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/queries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all queries */
    get: operations["listQueries"];
    put?: never;
    /** Create a query (seeds existing results silently) */
    post: operations["createQuery"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/queries/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["QueryId"];
      };
      cookie?: never;
    };
    /** Get a query and its results */
    get: operations["getQuery"];
    put?: never;
    post?: never;
    /** Delete a query and its results */
    delete: operations["deleteQuery"];
    options?: never;
    head?: never;
    /** Partially update a query (enabled, cron, or excludedIndexers) */
    patch: operations["updateQuery"];
    trace?: never;
  };
  "/queries/{id}/run": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["QueryId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run a query now (interactive priority) */
    post: operations["runQuery"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit an ad-hoc preview search */
    post: operations["searchPreview"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs/{jobId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    /** Poll a search job's status and results */
    get: operations["getJob"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/queue-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live work-queue state for UI polling */
    get: operations["getQueueStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/indexers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List configured Prowlarr indexers */
    get: operations["listIndexers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current settings */
    get: operations["getSettings"];
    /** Replace settings */
    put: operations["putSettings"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/settings/test-prowlarr": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test connectivity to a Prowlarr instance */
    post: operations["testProwlarr"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/settings/test-apprise": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a test Apprise notification */
    post: operations["testApprise"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Query: {
      id: number;
      name: string;
      query: string;
      cron: string | null;
      enabled: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastRun: string | null;
      /** Format: date-time */
      nextRun: string | null;
      lastCount: number | null;
      lastError: string | null;
      /** Format: date-time */
      lastNewResult: string | null;
      /** @description null means: inherit the default exclusion list from Settings */
      excludedIndexers: number[] | null;
    };
    QueryDetail: components["schemas"]["Query"] & {
      results: components["schemas"]["Result"][];
    };
    Result: {
      id: number;
      resultHash: string;
      title: string | null;
      indexer: string | null;
      size: number | null;
      guid: string | null;
      infoUrl: string | null;
      downloadUrl: string | null;
      seeders: number | null;
      /** Format: date-time */
      firstSeen: string;
      isNew: boolean;
    };
    PreviewResult: {
      title?: string | null;
      indexer?: string | null;
      size?: number | null;
      seeders?: number | null;
      guid?: string | null;
      infoUrl?: string | null;
      downloadUrl?: string | null;
    };
    CreateQueryRequest: {
      query: string;
      name?: string;
      cron?: string;
    };
    UpdateQueryRequest: {
      enabled?: boolean;
      cron?: string | null;
      excludedIndexers?: number[] | null;
    };
    Job: {
      /** @enum {string} */
      status: "queued" | "running" | "retrying" | "done" | "error";
      error?: string;
      results?: components["schemas"]["PreviewResult"][];
    };
    QueueStatus: {
      queries: {
        [key: string]: "queued" | "running";
      };
      /** @enum {string|null} */
      preview: "queued" | "running" | null;
    };
    Indexer: {
      id: number;
      name: string;
      enable: boolean;
    };
    Settings: {
      prowlarrUrl: string;
      prowlarrApiKey: string;
      prowlarrExternalUrl: string;
      defaultCron: string;
      minQueryInterval: number;
      maxRetries: number;
      prowlarrTimeout: number;
      appriseUrls: string;
      defaultExcludedIndexers: number[];
    };
    TestResult: {
      ok: boolean;
      message: string;
    };
    ProblemDetails: {
      type?: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
      errors?: {
        [key: string]: string[];
      };
    };
  };
  responses: {
    /** @description RFC 9457 problem details */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
    };
  };
  parameters: {
    QueryId: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listQueries: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Query"][];
        };
      };
    };
  };
  createQuery: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateQueryRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Query"];
        };
      };
      400: components["responses"]["Problem"];
    };
  };
  getQuery: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["QueryId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueryDetail"];
        };
      };
      404: components["responses"]["Problem"];
    };
  };
  deleteQuery: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["QueryId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components["responses"]["Problem"];
    };
  };
  updateQuery: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["QueryId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateQueryRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Query"];
        };
      };
      404: components["responses"]["Problem"];
    };
  };
  runQuery: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["QueryId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components["responses"]["Problem"];
    };
  };
  searchPreview: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          query: string;
        };
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            jobId: string;
          };
        };
      };
      400: components["responses"]["Problem"];
    };
  };
  getJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      404: components["responses"]["Problem"];
    };
  };
  getQueueStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueStatus"];
        };
      };
    };
  };
  listIndexers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            indexers: components["schemas"]["Indexer"][];
          };
        };
      };
      400: components["responses"]["Problem"];
      502: components["responses"]["Problem"];
    };
  };
  getSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
    };
  };
  putSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Settings"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
    };
  };
  testProwlarr: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          prowlarrUrl?: string;
          prowlarrApiKey?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestResult"];
        };
      };
    };
  };
  testApprise: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          appriseUrls?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestResult"];
        };
      };
    };
  };
}
